
GET http://localhost:5000/api/auth/v1/user

###
POST http://localhost:5000/api/auth/v1/register
Content-Type: application/json

{
    "username": "benjamin",
    "password": "123456"
}

###
POST http://localhost:5000/api/auth/v1/login
Content-Type: application/json

{
    "username": "benjamin",
    "password": "123456"
}